INSERT INTO IDENTITY (ID) VALUES (1);
INSERT INTO IDENTITY (ID) VALUES (2);
INSERT INTO IDENTITY (ID) VALUES (3);
INSERT INTO IDENTITY (ID) VALUES (4);


INSERT INTO USER (ID, FIRSTNAME, LASTNAME, EMAIL, LOGIN, PASSWORD) VALUES (1, 'alex', 'synclar', 'user1@atosorigin.com', 'admin', 'nwCxqV005XMHxW4oPNWmZE5MNXqH31sJ');
INSERT INTO USER (ID, FIRSTNAME, LASTNAME, EMAIL, LOGIN, PASSWORD) VALUES (2, 'test', 'ing', 'test@atosorigin.com', 'test', 'lvxWgeRR8QOakoGHnYAdxmW1ujQaauua');

INSERT INTO USERSGROUP (ID, NAME) VALUES (3, 'IM-ADMINS');
INSERT INTO USERSGROUP (ID, NAME) VALUES (4, 'IM-USERS');

INSERT INTO USER_GROUP ( GROUPS_ID , USERS_ID ) VALUES ( 3, 1 );
INSERT INTO USER_GROUP ( GROUPS_ID , USERS_ID ) VALUES ( 4, 1 );
INSERT INTO USER_GROUP ( GROUPS_ID , USERS_ID ) VALUES ( 4, 2 );

INSERT INTO IDENTITY_PERMISSIONS (IDENTITY_ID, PERMISSIONS) VALUES ( 3 , 'IM-ADMIN');
INSERT INTO IDENTITY_PERMISSIONS (IDENTITY_ID, PERMISSIONS) VALUES ( 4 , 'IM-USER');

