var URLS = {
    endPointURL: "api/authorize/token",
    templateUserList: "components/user/list.html",
    templateUserEdit: "components/user/edit.html",
    templateUserLogin: "components/user/login.html",
    templateUserHome: "components/user/Home.html",
	templateUserGroupsList : "components/generic/groupsList.html",
	templateUserPermissionsList : "components/generic/permissionsList.html",
    templateUserView: "components/user/view.html",
	templateUserPassword : "components/user/editPassword.html",
    templateGroupEdit: "components/group/edit.html",
    templateGroupList: "components/group/list.html",
    templateGroupView: "components/group/view.html",
	templateGroupGroupsList : "components/generic/groupsList.html",
	templateGroupPermissionsList : "components/generic/permissionsList.html",
	templateGenericPermissionsCheckBox : "components/generic/permissionsCheckBox.html",
    templateMain: "main.html",
	
    jsUserList: "http://localhost:8080/identity/components/user/list.js",
    jsUserEdit: "http://localhost:8080/identity/components/user/edit.js",
    jsUserView: "http://localhost:8080/identity/components/user/view.js",
    jsUserLoginForm: "http://localhost:8080/identity/components/user/login.js",
    jsUserLoginProcess: "http://localhost:8080/identity/components/user/postLogin.js",
    jsUserLogout: "http://localhost:8080/identity/components/user/logout.js",
	jsUserGroupsList : "http://localhost:8080/identity/components/user/groupsList.js",
	jsUserPassword: "http://localhost:8080/identity/components/user/editPassword.js",
	jsUserPermissionsList : "http://localhost:8080/identity/components/user/permissionsList.js",
	
    jsGroupList: "http://localhost:8080/identity/components/group/list.js",
    jsGroupEdit: "http://localhost:8080/identity/components/group/edit.js",
	jsGroupGroupsList : "http://localhost:8080/identity/components/group/groupsList.js",
    jsGroupPermissionsList : "http://localhost:8080/identity/components/group/permissionsList.js",
	
    apiUser: "https://localhost:8443/identity/api/user/", 
	apiUserName: "https://localhost:8443/identity/api/user/name/",
	apiUserPassword : "https://localhost:8443/identity/api/user/password/",
	
    apiUserCurrentUser: "https://localhost:8443/identity/api/user/me/",
    apiUserList: "https://localhost:8443/identity/api/user/all/",
    apiUserGroupsList: "/groups/",
	apiUserPermissionsList: "/permissions/",
	
	apiGroupName : "https://localhost:8443/identity/api/group/name/",
    apiGroup: "https://localhost:8443/identity/api/group/",
    apiGroupList: "https://localhost:8443/identity/api/group/list/",
	apiGroupGroupsList: "/groups/",
	apiGroupPermissionsList: "/permissions/",
	
};
